# use via:
# conda env create --name $NEW_ENV_NAME --file $THIS_FILE_NAME
# e.g.
# conda env create --name slic --file conda-env.yml
# NOTE: $NEW_ENV_NAME is optional and defaults to slic

name: slic
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bitshuffle>=0.5.2
  - bottleneck
  - colorama
  - dbus-python
  - fuzzywuzzy
  - ipython
  - loguru
  - logzero
  - matplotlib
  - numpy
  - pcaspy
  - pika
  - pint
  - playsound
  - pyepics>=3.4.2
  - pytest
  - rich
  - scipy
  - tqdm
  - wxpython
  - yaspin
  - paulscherrerinstitute::bsread
  - paulscherrerinstitute::cam_server_client
  - paulscherrerinstitute::cta_lib
  - paulscherrerinstitute::data_api
  - paulscherrerinstitute::diffcalc-core
  - paulscherrerinstitute::elog
  - paulscherrerinstitute::jungfrau_utils>=3.16.0
  - paulscherrerinstitute::sfdata

