{% set data = load_setup_py_data() %}

package:
    name: slic
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - bsread
        - cam_server_client
        - colorama
        - data_api
        - detector_integration_api
        - elog
        - ipython
        - jungfrau_utils
        - pyepics
        - tqdm


